#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -I$(srctree)/drivers/misc/mediatek/ai_device_check
ccflags-y += -I$(srctree)/drivers/misc/mediatek/

obj-y += ai_device_check.o
