ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/$(CONFIG_TOUCHSCREEN_MTK_ILITEK_SPI)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/base
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include








obj-y += ilitek_main.o \
	ilitek_spi.o \
	ilitek_plat_mtk.o \
	ilitek_ic.o \
	ilitek_touch.o \
	ilitek_mp.o \
	ilitek_hostdl.o \
	ilitek_node.o

