#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += s5kgm1stmipiraw_Sensor.o
# Antaiui <AI_BSP_CAM> <xieht> <2021-01-29> move to mtk arch begin
#obj-y += s5kgm1st_eeprom.o
# Antaiui <AI_BSP_CAM> <xieht> <2021-01-29> move to mtk arch end
