#
# Makefile for all kinds of Fingerprint
#
#Antaiui <AI_BSP_FINGER> <hehl> <2022-01-04> add icn finger for 2008 begin
obj-$(CONFIG_AI_BSP_ICN_FINGERPRINT) += fpsensor/
obj-$(CONFIG_FOCALTECH_FINGERPRINT)+=focaltech/
#Antaiui <AI_BSP_FINGER> <hehl> <2022-01-04> add icn finger for 2008 end
#Antaiui <AI_BSP_FINGER> <hehl> <2022-02-16> add sunwave finger for 2003 begin
obj-$(CONFIG_AI_BSP_SW330_FINGERPRINT) += ai_sw330/
#Antaiui <AI_BSP_FINGER> <hehl> <2022-02-16> add sunwave finger for 2003 end